### ISSUE TITLE
Fix configure check for FileCheck

### ISSUE THREAD

**Issue by bondhugula** [bondhugula/pluto#41]
configure currently checks in /usr/lib64/llvm. Also, check based on --with-clang-prefix value. 

https://github.com/bondhugula/pluto/commit/92805656c9d56d00a6b33bcd1728aa2e0c72e3dc#r33498148

**Comment by bondhugula** [comment]
Fixed in a46b60b0003f59d62e471a5a9ba008e4c392b1de

**Comment by georgebisbas** [comment]
Dear Pluto developers,

I am trying to install pluto in my home directory
on an Ubuntu 19.04. With LLVM and LLVM Filecheck installed.
Although I can see that this issue was resolved in the past, I still cannot get pluto to see the FileCheck installation.
Any help on that?

Thank you in advance,
George Bisbas

**Comment by bondhugula** [comment]
Could you say where you have FileCheck installed?

$ which FileCheck

Per configure.ac, pluto is looking for it in your path, /usr/lib64/llvm/ and CLANG_PREFIX/bin if a clang prefix was provided.

**Comment by georgebisbas** [comment]
Thank you for the very quick response.

$which FileCheck 
is not returning something.
I can tell that I have FileCheck
in 
/usr/lib/llvm-6.0/bin

**Comment by bondhugula** [comment]
> Thank you for the very quick response.
> 
> `$which FileCheck`
> is not returning something.
> I can tell that I have FileCheck
> in
> `/usr/lib/llvm-6.0/bin`

configure isn't checking there. If you just put this in your PATH, it'll find it. We could add an option though for configure to pass the FileCheck location.

**Comment by georgebisbas** [comment]
Thank you very much for the quick response.
I will update soon.
